# Generated by Django 2.1 on 2018-09-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('dob', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
