# Generated by Django 2.1 on 2018-12-29 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldone', models.CharField(max_length=50)),
                ('fieldtwo', models.CharField(max_length=50)),
                ('fieldthree', models.CharField(default='test', max_length=50)),
            ],
            options={
                'db_table': 'testdata',
            },
        ),
        migrations.CreateModel(
            name='userdatatable',
            fields=[
                ('useruniqueid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('dob', models.DateField()),
            ],
            options={
                'db_table': 'userdatatable',
            },
        ),
    ]
